name: release

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-20.04
            system: linux
            arch: x64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Calculate version
        run: curl -Ls https://solugo.github.io/gitversion/run.sh | GITVERSION=v0.0.7 bash
      - name: Build
        run: ./gradlew clean linkReleaseExecutable
      - name: Prepare Release for Linux
        if: matrix.system == 'linux'
        run: |
          mkdir "${GITHUB_WORKSPACE}/release"
          cp "${GITHUB_WORKSPACE}/build/bin/native/releaseExecutable/gitversion.kexe" "${GITHUB_WORKSPACE}/release/gitversion-${{ matrix.config.system }}-${{ matrix.config.arch }}"
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: |
            "${GITHUB_WORKSPACE}/release/*"
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/bin/native/releaseExecutable/gitversion.kexe
          asset_content_type: application/octet-stream
          asset_name: gitversion-${{ matrix.config.system }}-${{ matrix.config.arch }}
