name: release

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Calculate version
        run: curl -Ls https://solugo.github.io/gitversion/run.sh | GITVERSION=v0.0.7 bash
      - name: Build
        run: ./gradlew clean linkReleaseExecutable
      - name: Prepare Release
        run: |
          mkdir "release"
          cp "build/bin/linuxX64/releaseExecutable/gitversion.kexe" "release/gitversion-linux-x64"
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: |
            release/gitversion-linux-x64
